/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javaFxProject;

import javaFxProject.gui.view.userAuthentication.UserAuthenticationViewModel;
import org.junit.Test;
import org.assertj.core.api.Assertions;
import static org.junit.Assert.*;

public class ViewModelTests {
//    @Test
//    public void when_username_is_empty_then_login_should_be_disabled() {
//        UserAuthenticationViewModel viewModel = new UserAuthenticationViewModel();
//        viewModel.enteredUsername().setValue("login");
//        viewModel.enteredPassword().setValue("password");
//
//        viewModel.enteredUsername().setValue("");
//
//        Assertions.assertThat(viewModel.cannotRequestLogin().getValue()).isTrue();
//    }
}
